/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
	
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    public void testPrintName() {
        Library classUnderTest = new Library();
    	assertTrue("show get real name.", "xquan-gradle-sample".equals(classUnderTest.printName()));
    }
}
